[package]
name        =  "pyvm"
version     =  "0.0.1"
description =  "Python VM in Rust"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license     =  "MIT"
repository  =  "https://github.com/ponyatov/pyvm"
edition     =  "2024"

[dependencies]
# const_format = "0.2"

[target.'cfg(all(target_os = "linux"))'.dependencies]
# libc = "0.2"
